# Generated by Django 4.0.6 on 2022-07-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newss_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='newss',
            name='img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
